name: 'Test Action'
description: 'Test the modified modules'
inputs:
  token:
    description: 'The GitHub access token'
    required: true
outputs:
  modified_modules:
    description: 'An array of modified modules (top-level directories) formatted as JSON'
runs:
  using: 'node12'
  main: 'dist/index.js'
