# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run my custom script
      uses: ./.github/actions/my-action
      id: my-action
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Post a comment
      uses: ./.github/actions/comment
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        modified_modules: steps.my-action.outputs.modified_modules

    - name: Set up JDK 1.8
      if: ${{contains(fromJson(steps.my-action.outputs.modified_modules), 'other-module')}}
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache Maven dependencies
      if: success() # only run if previous step ran
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        # if there is no cache entry for the key, we can restore a previous cache with a partial key match
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      if: success() # only run if previous step ran
      run: mvn -B package --file pom.xml
